### ISSUE TITLE
不兼容pip10。。。

### ISSUE THREAD

**Issue by liudl** [ricequant/rqopen-client#4]
pip3 install rqopen-client
Collecting rqopen-client
  Using cached https://files.pythonhosted.org/packages/3b/93/00c4794f3513e78091b7b18ba26c80565a64379ff1931119ff5554160878/rqopen-client-0.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/1_/pvh3j4y12gj6nlx1mq0_vkrw0000gn/T/pip-install-61jnf85f/rqopen-client/setup.py", line 10, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'

**Comment by shidenggui** [comment]
fix by 1e7d75093b0f4e3e218cc4270ea21dfecaff5ca9
